// <auto-generated />
using System;
using Cycle.QUERY.INFRASTRUCTURE.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MES_Cycle.QUERY.INFRASTRUCTURE.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cycle.QUERY.DOMAIN.Entities.CycleEntity", b =>
                {
                    b.Property<Guid>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finished")
                        .HasColumnType("int");

                    b.Property<string>("MachineConfigId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parts_per_cycle")
                        .HasColumnType("int");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("int");

                    b.HasKey("CycleId");

                    b.ToTable("Cycle");
                });

            modelBuilder.Entity("Cycle.QUERY.DOMAIN.Entities.MachineConfigEntity", b =>
                {
                    b.Property<Guid>("MachineConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cycle_duration")
                        .HasColumnType("int");

                    b.Property<int>("Grit")
                        .HasColumnType("int");

                    b.Property<int>("MachineIdSeq")
                        .HasColumnType("int");

                    b.Property<string>("Operator_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pressure")
                        .HasColumnType("int");

                    b.Property<DateTime>("timeConig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MachineConfigId");

                    b.ToTable("MachineConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
